import math

import torch
import torch.nn as nn

from Flows.mades import GaussianMadeBN


class MaskedAutoregressiveFlow(nn.Module):
    """
        Implements a Masked Autoregressive Flow, which is a stack of mades such that the random numbers which drive made i
        are generated by made i-1. The first made is driven by standard gaussian noise. In the current implementation, all
        mades are of the same type. If there is only one made in the stack, then it's equivalent to a single made.
        """
    def __init__(self, in_size, hidden_sizes, n_mades, batch_norm=True):
        super(MaskedAutoregressiveFlow, self).__init__()
        self.bn = batch_norm
        self.models = nn.ModuleList([])
        order = lambda ind: 'default' if ind == 0 else 'reverse'
        for i in range(n_mades):
            self.models.append(GaussianMadeBN(in_size, hidden_sizes, order(i)))

        self.embed_size = in_size
        self.mean_log_std = nn.Parameter(torch.zeros(1, self.embed_size * 2))

    def log_lik(self, x, mean, log_sigma):
        tmp = math.log(2 * math.pi) + 2 * log_sigma + (x - mean).pow(2) * torch.exp(-2 * log_sigma)
        ll = -0.5 * tmp
        return ll

    def forward(self, x):
        out = x
        log_det_du_dx = 0.
        for i, layer in enumerate(self.models):
            log_det_inverse, u = layer(out)
            log_det_du_dx += log_det_inverse
            out = u

        mean, log_sigma = torch.split(self.mean_log_std, split_size_or_sections=self.embed_size, dim=-1)

        # print(log_det_du_dx)
        #log_probs = torch.sum(-0.5 * (math.log(2 * math.pi) + u**2), dim=1) + log_det_du_dx
        log_probs = torch.sum(self.log_lik(u, mean, log_sigma), dim=1) + log_det_du_dx
        return log_probs  #, u

    # def reverse(self, u):
    #     with torch.no_grad():
    #         for i, layer in enumerate(reversed(self.models)):
    #             u = layer.reverse(u)
    #     return u


if __name__ == '__main__':
    m = MaskedAutoregressiveFlow(in_size=4, hidden_sizes=(8,), n_mades=1, batch_norm=True)
    x = torch.randn(5, 4)
    ll, u = m(x)
    print(ll)
    print(u)
